#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: Tue May 26 10:39:01 UTC 2015
#
#  https://github.com/harisekhon/nagios-plugin-kafka
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

language: scala
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

scala:
  - 2.9.3
  - 2.10.4
  - 2.11.2

# This will follow make to ensure that we have built the Java submodule library required as an SBT unmanaged dep
before_install:
  - make

#sudo: required

notifications:
  email: false

branches:
  only:
    - master

script:
  - make test

services:
  - docker

after_success:
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/nagios-plugin-kafka/trigger/76a766f5-1ba8-4189-a2ae-d62a62c2d8d4
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/nagios-plugins/trigger/5b0d1a59-8b53-466a-87d7-8e99dfd01f16/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/centos-github/trigger/316d1158-7ffb-49a4-a7bd-8e5456ba2d15/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/ubuntu-github/trigger/abd4dbf0-14bc-454f-9cde-081ec014bc48/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/debian-github/trigger/0cfb3fe7-2028-494b-a43b-068435e6a2b3/
