//  vim:ts=4:sts=4:sw=4:et
//
//  Author: Hari Sekhon
//  Date: 2016-06-28 14:14:18 +0100 (Tue, 28 Jun 2016)
//
//  https://github.com/harisekhon/nagios-plugin-kafka
//
//  License: see accompanying Hari Sekhon LICENSE file
//
//  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
//
//  https://www.linkedin.com/in/harisekhon
//

// Config for each Kafka broker
KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="test_kafka_admin"
    password="test_kafka_pass"
    user_test_user1="test_kafka_pass"
    user_test_user2="test_kafka_pass"
    user_test_kafka_admin="test_kafka_pass"
;
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="test_user1"
    password="test_kafka_pass"
;
};

// Zookeeper client authentication
Client {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    doNotPrompt=true
    useTicketCache=false
    keyTab="/etc/security/keytabs/kafka_server.keytab"
    principal="kafka/kafka1.hostname.com@EXAMPLE.COM";
};
